server:
  port: 8888
spring:
  application:
    name: porn-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://30.1.12.1:3306/develop?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: qwer@1234!
    initial-size: 5
    min-idle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionErrorRetryAttempts: 3
    breakAfterAcquireFailure: true
    timeBetweenConnectErrorMillis: 300000
    asyncInit: true
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    transaction-query-timeout: 6000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: mktime_123
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:com/porn/**/mapper/*.xml
swagger:
  enable: false
minio:
  url: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: demo
  cdnUrl: http://usjsgdj.b-cdn.net/demo
  url1: http://127.0.0.1:9000
  accessKey1: minioadmin
  secretKey1: minioadmin
  bucketName1: demo
dingding:
  botUsername: upeaksu_bot
  botToken: 6491224325:AAFNxOvN8maNXlMx-SvX4YJ_wAPMBheDTT0
  chatId: 1175508779







